# Generated by Django 5.2.17 on 2026-09-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('BI', 'Data & BI'), ('SYSTEMS', 'Data Engineering & Systems'), ('DESIGN', 'Technical & Graphic Design'), ('OPS', 'Logistics & Operations'), ('QUALITY', 'Quality Management'), ('ANALYTICS', 'Data Analytics')], max_length=20),
        ),
    ]
